## environment-dev

## tomcat server
server:
  port: 8088


spring:
  ## datasource
  datasource:
    url: "jdbc:mysql://192.168.100.100:3306/demo?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true\
      &useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=true&allowMultiQueries=true&autoReconnect=true"
    username: root
    password: root
  # redis
  redis:
    database: 1
    host: 192.168.100.100
    port: 7749
    password: 21cde022-a5da-626e-c8f4-04c99ed3a181
    timeout: 10000ms
    jedis:
      pool:
        max-active: 200
        max-idle: 500
        min-idle: 50
        max-wait: 100s
  # rabbitmq
  rabbitmq:
    host: 192.168.100.100
    port: 5672
    username: rabbitmqadmin
    password: rootpass100

# yml demo
person:
  name: Tom
  age: 40
  parent:
    mother:
      name: Lily
      age: 65
    father:
      name: Bob
      age: 68

# Swagger config
swagger:
  enable: true

## aliyun oss
## 配置说明参考: com.ljq.demo.springboot.common.config.OSSConfig.class
oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  url: https://xxxx.oss-cn-hangzhou.aliyuncs.com/
  accessKeyId: your_accessKey_id
  accessKeySecret: your_accessKey_secret
  bucketName: your_bucket_name



