# tomcat server
server:
  port: 8088

# spring cloud
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


## datasource
spring:
    datasource:
      url: "jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true\
        &useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=true&allowMultiQueries=true&autoReconnect=true"
      username: root
      password: sasa
      driver-class-name: com.mysql.jdbc.Driver
    application:
      name: demo-server  # spring cloud server center ID





## mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ljq.demo.springboot.entity


