## environment-test

## datasource
spring:
  datasource:
    url: "jdbc:mysql://192.168.6.109:13306/demo?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true\
      &useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=true&allowMultiQueries=true&autoReconnect=true"
    username: root
    password: sasa